### ISSUE TITLE
BleakError: Device not found

### ISSUE THREAD

**Issue by lvaecairn** [adafruit/Adafruit_CircuitPython_BLE_iBBQ#8]
I am trying to run the INKBIRD Smart Wireless BBQ Thermometer. It correctly finds the iBBQ advertisement but then throws `bleak.exc.BleakError: Device with address FC:45:C3:38:76:03 was not found.` Does anyone know how this might be addressed?

**Comment by dhalbert** [comment]
What is your host computer and what version of its OS are you running? Sometimes things break for `bleak`, the underlying BLE layer we use, because of changes in the host OS. This has been particularly true for macOS. I need to retest with the latest bleak. Right now I pin bleak to its version 0.11.0.

It is also possible your thermometer simply does not work the same ways as the one I originally tested and coded for.

**Comment by lvaecairn** [comment]
I am using Microsoft Windows 10.0.19042 on an Omen laptop. I am currently using bleak 0.11.0; might it help to update it? If so, to which version? I thought I was having problems earlier with being able to scan the device but not detect it (but we are definitely not confident about that).

**Comment by dhalbert** [comment]
The API of bleak has been changing, so just upgrading will probably not work. You could also test this with an nRF52840 board and native Circuitptyon, if you have one, to take bleak out of the picture.

**Comment by dhalbert** [comment]
By the way, Windows 10.0.19042 is the 20H2 release (fall 2020), which is two major upgrades behind 21H2, which is now available.

**Comment by lvaecairn** [comment]
Ahh. I see. I didn´t immediately realize bleak wasn´t part of the CircuitPython environment (this is my first CircuitPython project). I was trying to figure out how bleak tied into CircuitPython before. Now it makes a lot more sense. Thank you

**Comment by lvaecairn** [comment]
Hi again, I have obtained a board and have successfully connected a terminal and run some code (although I'm having some trouble figuring out circuitpython's pin references still). Could you explain how to get this project to run on the board and output bluetooth information?  I just don't completely understand where I am supposed to copy files and what files to copy. 

Thanks.

**Comment by dhalbert** [comment]
GitHub is for bug reports and enhancement requests, and not really for support. Could you instead ask:
1. in our forums: https://forums.adafruit.com/viewforum.php?f=60
2. or in discord: https://adafru.it/discord

**Comment by tekktrik** [comment]
Closing as a support-related issue.
